server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: meta-data-store
        uri: lb://meta-data-store
        predicates:
        - Path=/mds/**
        filters:
        - RewritePath=/mds/(?<path>.*), /$\{path}
        
      - id: mysql-server
        uri: lb://mysql-server
        predicates:
        - Path=/mysql/**
        filters:
        - RewritePath=/mysql/(?<path>.*),/$\{path}

   
